#!/bin/sh

set -e

# empty message of the day.
echo -n > /etc/motd

# remove some unused packages
DEBIAN_FRONTEND=noninteractive apt-get purge -y laptop-detect tasksel emacsen-common ienglish-common ispell

# install some additional packages
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends openssh-server sudo 

# members of `sudo` group are not asked for password.
sed -i 's/^%sudo\tALL=(ALL:ALL) ALL/%sudo\tALL=(ALL:ALL) NOPASSWD:ALL/' /etc/sudoers

# new users should be put into the "users" group
sed -i 's/^USERGROUPS=yes/USERGROUPS=no/' /etc/adduser.conf

# fix the time server configuration
sed -i 's/^#NTP=/NTP=us.pool.ntp.org/' /etc/systemd/timesyncd.conf

# unpack the postinstall tar file
tar -z -x -C /tmp -f /tmp/postinstall.tar.gz

# install global things and root things
mkdir -m700 -p /root/.ssh
cp /tmp/postinstall.d/resolv.conf /etc/resolv.conf
cp /tmp/postinstall.d/apt.conf.d/50unattended-upgrades /etc/apt/apt.conf.d/50unattended-upgrades
cp /tmp/postinstall.d/apt.conf.d/20auto-upgrades /etc/apt/apt.conf.d/20auto-upgrades
cp /tmp/postinstall.d/vimrc /root/.vimrc
cp /tmp/postinstall.d/bash_login /root/.bash_login

# add our sudoers file for drew
cp /tmp/postinstall.d/sudoers /etc/sudoers.d/drew
chmod 400 /etc/sudoers.d/drew

# install ssh keys and other things for drew user
mkdir -m700 -p /home/drew/.ssh
cp /tmp/postinstall.d/authorized_keys /home/drew/.ssh/authorized_keys
cp /tmp/postinstall.d/vimrc /home/drew/.vimrc
cp /tmp/postinstall.d/bash_login /home/drew/.bash_login

# fix permissions on root home directory
chmod 700 /root
chmod 600 /root/.bash_login

# fix permissions on drew home directory
chown -R drew:drew /home/drew
chmod 700 /home/drew
chmod 600 /home/drew/.bash_login /home/drew/.ssh/authorized_keys

git config set user.name "Drew Swanner"
git config set user.email "drew@drewswanner.dev"

